In [2]:
import numpy as np

In [3]:
n = np.array([[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]])
print(n)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [4]:
x = np.arange(20).reshape(4,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [5]:
 y = x[0: 4: 2]
y

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [6]:
z = y[0: : 2, 0: : 2]
z

array([[0, 2, 4]])

In [7]:
t = y[1: : 2, 0: : 2]
t

array([[10, 12, 14]])

In [8]:
b = z, t

In [9]:
b

(array([[0, 2, 4]]), array([[10, 12, 14]]))

In [11]:
print(f'b에 저장된 객체들은 {b} 입니다')

b에 저장된 객체들은 (array([[0, 2, 4]]), array([[10, 12, 14]])) 입니다
